#!/bin/bash

#Prints a help message
function print_help {
	echo "Usage: $0 [options] --longreads LR.fasta --shortreads SR.fastq --out result.fasta --tmpdir tmp_directory"
	echo ""
	echo "	Input:"
	echo "	LR.fasta:	fasta file of long reads, one sequence per line."
	echo "	SR.fastq:	fastq file of short reads."
	echo "			Warning: only one file must be provided."
	echo "			If using paired reads, please concatenate them into one single file."
	echo "	result.fasta:	fasta file where to output the synthetic long reads."
	echo "	tmp_directoty:	directory where to store the temporary files."
	echo ""
	echo "	Options:"
	echo "	--kmer:		k-mer size for the graph construction (default: 64)."
	echo "	--seedsoverlap:	Minimum overlap length to allow the merging of two overlapping seeds (default: k-1)."
	echo "	--minoverlap:	Minimum overlap length to allow the exploration of an edge of the graph (default: k-5)."
	echo "	--backtracks:	Maximum number of backtracks (default: 1,125)."
	echo "	--seedskips:	Maximum number of seed skips (default: 5)."
	echo "	--bestn		Top alignments to be reported by BLASR (default: 10)."
	echo "			This parameter should be raised accordingly to the error rate of the long reads."
	echo "	--nproc		Number of processes to run in parallel (default: number of cores)."
	echo "	--help:		Print this help message."
	exit 1
}

#Set options to default values
longreads=""
LR=""
shortreads=""
SR=""
k=64
seedsoverlap=""
minoverlap=""
backtracks=1125
seedskips=5
bestn=10
nproc=$(nproc)
tmpdir=""
out=""

#Print help if no argument specified
if [[ "$1" == "" ]] ; then
	print_help
fi

#Otions handling
while [[ "$1" != "" ]] ; do
	case "$1" in
		"--help")
			print_help ;;
		"--longreads")
			case "$2" in
				"") echo "Error: $1 expects an argument" ; exit 1 ;;
				*) longreads="$2" ; LR=$(basename "$2") ; shift 2 ;;
			esac;;
		"--shortreads")
			case "$2" in
				"") echo "Error: $1 expects an argument" ; exit 1 ;;
				*) shortreads="$2" ; SR=$(basename "$2") ; shift 2 ;;
			esac ;;
		"--out")
			case "$2" in
				"") echo "Error: $1 expects an argument" ; exit 1 ;;
				*) out="$2" ; shift 2 ;;
			esac ;;
		"--tmpdir")
			case "$2" in
				"") echo "Error: $1 expects an argument" ; exit 1 ;;
				*) tmpdir="$2" ; shift 2 ;;
			esac ;;
		"--kmer")
			case "$2" in
				"") echo "Error: $1 expects an argument" ; exit 1 ;;
				*) k="$2" ; shift 2 ;;
			esac ;;
		"--seedsoverlap")
			case "$2" in
				"") echo "Error: $1 expects an argument" ; exit 1 ;;
				*) seedsoverlap="$2" ; shift 2 ;;
			esac ;;
		"--minoverlap")
			case "$2" in
				"") echo "Error: $1 expects an argument" ; exit 1 ;;
				*) minoverlap="$2" ; shift 2 ;;
			esac ;;
		"--backtracks")
			case "$2" in
				"") echo "Error: $1 expects an argument" ; exit 1 ;;
				*) backtracks="$2" ; shift 2 ;;
			esac ;;
		"--seedskips")
			case "$2" in
				"") echo "Error: $1 expects an argument" ; exit 1 ;;
				*) seedskips="$2" ; shift 2 ;;
			esac ;;
		"--bestn")
			case "$2" in
				"") echo "Error: $1 expects an argument" ; exit 1 ;;
				*) bestn="$2" ; shift 2 ;;
			esac ;;
		"--nproc")
			case "$2" in
				"") echo "Error: $1 expects an argument" ; exit 1 ;;
				*) nproc="$2" ; shift 2 ;;
			esac ;;
    		--)
			shift ; break ;;
    		*)
			echo "Error: invalid option \"$1\"" ; exit 1 ;;
  	esac
done

#If seedsoverlap or minoverlap haven't been set, set them to default values
if [[ $seedsoverlap = "" ]] ; then
	seedsoverlap=$((k-1))
fi
if [[ $minoverlap = "" ]] ; then
	minoverlap=$((k-5))
fi

#Exit if no short reads, no long reads, or no output files have been specified
if [[ $LR == "" ]] ; then
	echo "Error: --longreads must be specified";
	exit 1;
fi
if [[ $SR == "" ]] ; then
	echo "Error: --shortreads must be specified";
	exit 1;
fi
if [[ $out == "" ]] ; then
	echo "Error: --out must be specified";
	exit 1;
fi
if [[ $tmpdir = "" ]] ; then
	echo "Error: --tmpdir must be specified";
	exit 1;
fi

#Remove the output file if it already exists
if [[ -f $out ]] ; then
	rm $out
fi

#Create the directory for temporary files, if it does not exist
if [[ ! -d $tmpdir ]] ; then
        mkdir $tmpdir
fi

#Create the subdirectory for Alignments, if it does not exist
if [[ ! -d $tmpdir/Alignments ]] ; then
	mkdir $tmpdir/Alignments
fi


#Run the correction pipeline

aln="$SR_on_$LR"
seeds="seeds_"$$
formatLR="format_$LR"

echo "Correcting the short reads..."
quorum --prefix $tmpdir/quorum_corrected -q 33 -t "$nproc" "$shortreads"
echo "...Done"
rm $tmpdir/quorum_corrected.log
rm $tmpdir/quorum_corrected_mer_database.jf
echo "Extracting the short reads' k-mers and building the graph..."
./bin/filterShortReads.py $tmpdir/quorum_corrected.fa "$k" > $tmpdir/long_quorum_corrected.fa
rm $tmpdir/quorum_corrected.fa
revseq $tmpdir/long_quorum_corrected.fa -reverse -complement -outseq $tmpdir/RC_long_quorum_corrected.fa 2>> /dev/null
cat $tmpdir/long_quorum_corrected.fa $tmpdir/RC_long_quorum_corrected.fa > $tmpdir/all_long_quorum_corrected.fa
jellyfish count -m "$k" -s 500M -t "$nproc" -o $tmpdir/mer_counts.jf $tmpdir/all_long_quorum_corrected.fa
rm $tmpdir/RC_long_quorum_corrected.fa
rm $tmpdir/all_long_quorum_corrected.fa
jellyfish dump $tmpdir/mer_counts.jf > $tmpdir/"$k-mers-$SR"
rm $tmpdir/mer_counts.jf
sed -i '/>.*/d' $tmpdir/"$k-mers-$SR"
./bin/PgSAgen $tmpdir/"$k-mers-$SR" $tmpdir/"$k-mers-$SR" >> /dev/null 2>> /dev/null
echo "...Done"

echo "Aligning the short reads on the long reads..."
./bin/formatLongReads.py "$longreads" > $tmpdir/"$formatLR"
./bin/blasr $tmpdir/long_quorum_corrected.fa $tmpdir/"$formatLR" --nproc "$nproc" -m 6 --minAlnLength "$k" --bestn "$bestn" > $tmpdir/"$aln" 2>> /dev/null
rm $tmpdir/long_quorum_corrected.fa
sort -T $tmpdir/ -k 3 $tmpdir/"$aln" > $tmpdir/"tmp_$aln"
mv $tmpdir/"tmp_$aln" $tmpdir/"$aln"
./bin/filterOutShortAlignments.py $tmpdir/"$aln" "$k" $tmpdir/Alignments/
ls $tmpdir/Alignments/ > $tmpdir/"$seeds"
rm $tmpdir/"$aln"
echo "...Done"
echo "Generating the sythetic long reads..."
parallel -j "$nproc" ./bin/generateSLR $tmpdir "$k" $tmpdir/"$k-mers-$SR.pgsa" "$seedsoverlap" "$minoverlap" "$backtracks" "$seedskips" "$out" :::: $tmpdir/"$seeds"
echo "...Done"
echo "Removing temporary files..."
rm -Rf $tmpdir
echo "...Done"
